// AUTO-GENERATED by scripts/export-ui.ts — 관리자 '번역 관리'에서 수정한 UI/라벨 번역
// (app_settings i18n.<locale>.ui / i18n.<locale>.label)을 정적으로 병합한 오버라이드.
// 클라이언트 전역(헤더 등)에서 서버 fetch 없이 쓰기 위함. 수정 금지(스크립트가 덮어씀).
import type { Locale } from "./locale";

/** UI 사전(t) 오버라이드 — { locale: { key: text } } */
export const UI_OVERRIDES: Partial<Record<Locale, Record<string, string>>> = {};
/** 분류 라벨(tl) 오버라이드 — { locale: { "type.key": text } } */
export const LABEL_OVERRIDES: Partial<Record<Locale, Record<string, string>>> = {};
