// 번역된 이름(인물·장소·유적)을 정적 색인으로 추출 → lib/data/i18n-names.ts.
// 클라이언트 전역 헤더(둘러보기 패널)가 서버 fetch 없이 로케일 이름을 쓰도록.
// 번역 적재(translate.ts) 후 실행: tsx --env-file=.env.local scripts/export-names.ts
import { getServiceSupabase } from "../lib/db/supabase";
import { writeFileSync } from "node:fs";

// env 없으면(로컬 빌드 등) 기존 정적 파일 유지하고 건너뜀 — 빌드 실패 방지.
if (!process.env.SUPABASE_SERVICE_ROLE_KEY || !(process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL)) {
  console.log("export-names: SUPABASE env 없음 — 건너뜀(기존 i18n-names.ts 유지)");
  process.exit(0);
}
const db = getServiceSupabase();
const LOCALES = ["en", "mn"] as const;

async function rows(like: string) {
  const { data } = await db.from("app_settings").select("key,value").like("key", like);
  return (data ?? []) as { key: string; value: unknown }[];
}

async function main() {
  const out: Record<string, { person: Record<string, string>; place: Record<string, string>; heritage: Record<string, string> }> = {};
  for (const loc of LOCALES) {
    const person: Record<string, string> = {};
    for (const r of await rows(`i18n.${loc}.person.%`)) {
      const id = r.key.replace(`i18n.${loc}.person.`, "");
      const n = (r.value as { name?: string })?.name;
      if (n) person[id] = n;
    }
    const place: Record<string, string> = {};
    const pl = (await db.from("app_settings").select("value").eq("key", `i18n.${loc}.places`).maybeSingle()).data?.value;
    if (pl && typeof pl === "object") Object.assign(place, pl);
    const heritage: Record<string, string> = {};
    for (const r of await rows(`i18n.${loc}.heritage.%`)) {
      const id = r.key.replace(`i18n.${loc}.heritage.`, "");
      const n = (r.value as { name?: string })?.name;
      if (n) heritage[id] = n;
    }
    out[loc] = { person, place, heritage };
  }
  const body = `// AUTO-GENERATED by scripts/export-names.ts — 번역된 이름 정적 색인(클라 헤더용). 수정 금지.
import type { Locale } from "@/lib/i18n/locale";

type NameMap = { person: Record<string, string>; place: Record<string, string>; heritage: Record<string, string> };
export const I18N_NAMES: Partial<Record<Locale, NameMap>> = ${JSON.stringify(out, null, 2)};

/** 로케일 이름 조회(없으면 한국어 원본). type: person|place|heritage */
export function localName(locale: Locale, type: "person" | "place" | "heritage", id: string, ko: string): string {
  if (locale === "ko") return ko;
  return I18N_NAMES[locale]?.[type]?.[id] || ko;
}
`;
  writeFileSync("lib/data/i18n-names.ts", body, "utf8");
  console.log(`✓ lib/data/i18n-names.ts — en(person ${Object.keys(out.en.person).length}/place ${Object.keys(out.en.place).length}/heritage ${Object.keys(out.en.heritage).length}) · mn(person ${Object.keys(out.mn.person).length}/place ${Object.keys(out.mn.place).length}/heritage ${Object.keys(out.mn.heritage).length})`);
  process.exit(0);
}
main().catch((e) => { console.error("export-names 실패(건너뜀, 기존 파일 유지):", String(e).slice(0, 200)); process.exit(0); });
