// 관리자 '번역 관리'에서 저장한 UI/라벨 번역(app_settings i18n.<locale>.ui / .label)을
// 정적 오버라이드(lib/i18n/overrides.ts)로 추출. 클라이언트 전역에서 서버 fetch 없이 쓰기 위함.
// UI/라벨 번역 수정 후 실행: tsx --env-file=.env.local scripts/export-ui.ts → 빌드·배포.
import { getServiceSupabase } from "../lib/db/supabase";
import { writeFileSync } from "node:fs";

// env 없으면(로컬 빌드 등) 기존 정적 파일 유지하고 건너뜀 — 빌드 실패 방지.
if (!process.env.SUPABASE_SERVICE_ROLE_KEY || !(process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL)) {
  console.log("export-ui: SUPABASE env 없음 — 건너뜀(기존 overrides.ts 유지)");
  process.exit(0);
}
const db = getServiceSupabase();
const LOCALES = ["en", "mn"] as const;

async function getMap(key: string): Promise<Record<string, string>> {
  const { data } = await db.from("app_settings").select("value").eq("key", key).maybeSingle();
  const v = data?.value;
  return v && typeof v === "object" ? (v as Record<string, string>) : {};
}

async function main() {
  const ui: Record<string, Record<string, string>> = {};
  const label: Record<string, Record<string, string>> = {};
  for (const loc of LOCALES) {
    const u = await getMap(`i18n.${loc}.ui`);
    if (Object.keys(u).length) ui[loc] = u;
    const l = await getMap(`i18n.${loc}.label`);
    if (Object.keys(l).length) label[loc] = l;
  }
  const body = `// AUTO-GENERATED by scripts/export-ui.ts — 관리자 '번역 관리' UI/라벨 검수본 정적 병합. 수정 금지.
import type { Locale } from "./locale";

/** UI 사전(t) 오버라이드 — { locale: { key: text } } */
export const UI_OVERRIDES: Partial<Record<Locale, Record<string, string>>> = ${JSON.stringify(ui, null, 2)};
/** 분류 라벨(tl) 오버라이드 — { locale: { "type.key": text } } */
export const LABEL_OVERRIDES: Partial<Record<Locale, Record<string, string>>> = ${JSON.stringify(label, null, 2)};
`;
  writeFileSync("lib/i18n/overrides.ts", body, "utf8");
  console.log(`✓ lib/i18n/overrides.ts — ui(en ${Object.keys(ui.en ?? {}).length}/mn ${Object.keys(ui.mn ?? {}).length}) · label(en ${Object.keys(label.en ?? {}).length}/mn ${Object.keys(label.mn ?? {}).length})`);
  process.exit(0);
}
main().catch((e) => { console.error("export-ui 실패(건너뜀, 기존 파일 유지):", String(e).slice(0, 200)); process.exit(0); });
